name: Update Gantt Chart

on:
  schedule:
    - cron: '45 8 * * *'  # 매일 8시 45분에 실행
  workflow_dispatch:

jobs:
  update-gantt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install matplotlib python-dateutil requests

      - name: Generate Gantt Chart
        run: python generate_gantt_chart.py

      - name: Commit and Push Changes
        if: success()
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}  # PAT 사용
        run: |
          git config --local user.email "sonjh970226@gmail.com"  # 자신의 이메일
          git config --local user.name "SON1205"  # 자신의 이름
          git add charts/*.png
          git commit -m "Update Gantt Chart for $(date +'%Y-%m-%d')"
          git push https://x-access-token:${{ secrets.ACCESS_TOKEN }}@github.com/ssafy12-seoul07/PJT-FINAL-F-JH-HW.git main
